### PR TITLE
Tag crash

### PR DESCRIPTION
**Pull request by aleene**
## PR Description

Should prevent a crash when variable tag has a strange value.

Type of Changes 

- [x] Fixes Issue #274

Proposed changes

 User alternative URLS, which can be savely unwrapped

### CODE REVIEW

**Comment by teolemon** [comment]
Any example of a faulty url for a test ?

**Comment by aleene** [comment]
I am not sure what caused the crash. Maybe a tag with a space?

**Comment by philippeauriach** [comment]
I cannot check right now, but the commit looks weird, just default to an url without the tag in it ? Is does seems that it won’t crash but could result in weird results such as a user clicking a tag and ending on a page without tag ?

The proper solution would likely to find a case not working and fixing maybe the encoding so that it won’t crash and works properly ? If it is a problem of space and non allowed characters in url, then we juste have to url encode the tag before.

**Comment by teolemon** [comment]
Looking at it, I would say Spanish packager codes.
Try with this barcode:
image

**Comment by aleene** [comment]
Spanish barcode works.
I still like to commit this one just to be more crash proof.

**Pull request merged**
