### PR TITLE
Added a button next to the ingredients analysis icons

### LINKED ISSUE #763: Add a link to the ingredient analysis section of settings
Add a link to the ingredient analysis section of settings
We plan on adding many more analysis, so we need a scalable way to enable and disable them
(Also sorry for the mockup copy paste from Android)
image

### PR DESCRIPTION
**Pull request by aleene**
## PR Description
Added a button next to the ingredients analysis icons, which opens the corresponding settings.

## Screenshot
https://user-images.githubusercontent.com/1329905/95478287-a2b6f180-0989-11eb-806d-ab147571b9fc.jpeg

## Type of Changes 
- [X] Fixes Issue #763

### CODE REVIEW

**Comment by teolemon** [comment]
I'm really disturbed by the visual incoherence: the button is very small, not coherent with the other elements it impacts.

**Comment by aleene** [comment]
And what do you suggest? Something similar as the analysis icons?

**Comment by teolemon** [comment]
Yes. I think it's the most straightforward and coherent solution.

**Comment by aleene** [comment]
image

**Comment by teolemon** [comment]
@aleene I'm going to merge it. I still have a visual disagreement, but it does the job :-)

**Pull request merged**
