### PR TITLE
Delete duplicate localization files and fix en.lproj and nl.lproj paths

### PR DESCRIPTION
**Pull request by magauran**
- Delete duplicate Localizable.strings
- Move _nl_ and _en_ localizations to _Localization_ folder

Yes, it's almost the same as  #315

### CODE REVIEW

**Comment by teolemon** [comment]
Thanks for the PR
We need to update the Crowdin translation config as well in `crowdin.yml` since it currently is:
```
  - source: /Sources/en.lproj/Localizable.strings
    translation: /Sources/Localization/%two_letters_code%.lproj/Localizable.strings
```

**Comment by teolemon** [comment]
Also welcome @magauran :-)

**Review by philippeauriach — APPROVED** [review]

**Comment by teolemon** [comment]
@aleene does this look good to you ?

**Comment by aleene** [comment]
Is this still needed? #315 is committed.

**Review by aleene — COMMENTED** [review]
done

**Pull request merged**
