### PR TITLE
More visible edit button

### PR DESCRIPTION
**Pull request by pacocd**
## PR Description
Edit button has been moved from Product Summary bottom to Navigation bar right button.

Type of Changes 

- [x] Fixes Issue #[421]
- [ ] New feature

Proposed changes

  - There is a weird logic to add a share button, it's been deleted.
  - Moved Edit button to Navigation bar right button.
  - Remove SummaryFooterCellController since it's no longer required.
 
## Screenshots

image

### Before 
https://user-images.githubusercontent.com/21128742/67881930-080e2b80-fb07-11e9-9d50-4bba74bcd828.png
### After
https://user-images.githubusercontent.com/21128742/67881950-0e9ca300-fb07-11e9-98af-3e51b538c01a.png

## Checklist
 
Make sure you've done all the following (_Put an `x` in the boxes that apply._)
 
 - [x] If you have multiple commits please combine them into one commit by [squashing](https://github.com/todotxt/todo.txt-android/wiki/Squash-All-Commits-Related-to-a-Single-Issue-into-a-Single-Commit) them. 
 - [x] Code is well documented
 - [ ] Included unit tests for new functionality
 - [x] All user-visible strings are made translatable
 - [ ] Code passes Travis builds in your branch

### CODE REVIEW

**Comment by aleene** [comment]
Conflict needs to be resolved.

**Comment by teolemon** [comment]
Thank you very much @pacocd for your contribution to Open Food Facts 🎉

**Review by aleene — DISMISSED** [review]
This is an old one by now. Let's see if we can merge.

**Comment by teolemon** [comment]
@pacocd would it be possible to rebase the PR, I'd very much like to merge it :-)

**Comment by pacocd** [comment]
of course @teolemon will do later today :)
Sorry guys, I had email notifications deactivated and just got notice of messages in this PR 🤦‍♂️

**Comment by teolemon** [comment]
I based on develop. There are conflicts to solve.

**Comment by teolemon** [comment]
Bad rebase from me. There's some old stuff coming back like Crashlytics, needs an actual rebasing

**Comment by aleene** [comment]
@teolemon Can you have a go again. I will try to get this working again.

**Comment by aleene** [comment]
Now I need to find a way to open this as a remote

**Comment by aleene** [comment]
I will try to recreate this. Otherwise it is to complex.

**Comment by aleene** [comment]
See #776

**Pull request closed without merging**
