### PR TITLE
History of scanned products

### PR DESCRIPTION
**Pull request by tovkal**
Implementation of #33

### CODE REVIEW

**Comment by teolemon** [comment]
Can you display the Nutriscore as a color dot ? To have an overview of the nutritional quality of what you ate ?

**Comment by Tovkal** [comment]
I'm not sure what you mean @teolemon. The search history list is quite simple, product name and I thought of putting the search source below it (scan or text).

Something like this (missing the search source below the name, in smaller  

alt text

Do you want a small circle with the colour of the nutriscore value?

If you could do a little sketch or mockup, that would be most helpful.

**Comment by teolemon** [comment]
image
Here's the Android Refactor. Note the use of Name - Brand - Weight. Especially useful on "Nutella" queries.

**Comment by Tovkal** [comment]
Ok. Although to me, if I did not know what it represents, it would it be a bit confusing seeing the colour dots. Wouldn't it be better to show the nutriscore as a single letter (with the appropriate background colour)? Should the image also be included?

Also, should this search history be searchable (not sure if this screenshot is from search history or search results)? How long should items be stored, how many days?

**Comment by teolemon** [comment]
- Having the letter should make it more explicit than a mere color dot.
- Not sure that making it searchable is essential. This is indeed a screenshot from search results. Just for inspiration
- We have the photos in search in V1. We don't have any history in V1.
- On Android, the history is not limited in time (only stored locally), cool bonus: it can be exported as a CSV file.

**Pull request merged**
