### PR TITLE
Hide "City and country of purchase"

### LINKED ISSUE #727: Hide "City and country of purchase"
Hide "City and country of purchase". This does not bring any value to the user: 

- the field is returned as a slug
- we have the value 5% of the time.
- What's the point knowing that someone bought it in Lyons, France, when I'm in Paris France.

The only interesting field is "Countries" which is already shown below.

image

### PR DESCRIPTION
**Pull request by tejuamirthi**
Signed-off-by: tejuamirthi <tejuamirthi@gmail.com>

## PR Description
Made requested changes by not adding the city and country row

Fixes: #727 

Type of Changes 

- [X] Fixes Issue #727 

Proposed changes

  - Hide the city and country of purchase
 
##

 Screenshots

### Before 
Screenshot 2020-10-03 at 7 52 25 PM

### After
Screenshot 2020-10-03 at 7 51 44 PM

 
## Checklist
 
Make sure you've done all the following (_Put an `x` in the boxes that apply._)
 
 - [X] If you have multiple commits please combine them into one commit by [squashing](https://github.com/todotxt/todo.txt-android/wiki/Squash-All-Commits-Related-to-a-Single-Issue-into-a-Single-Commit) them. 
 - [X] Code is well documented

### CODE REVIEW

**Comment by tejuamirthi** [comment]
Hey @teolemon These checks are being shown from hours. I dont understand what's wrong. Please review this pr and confirm the outcome. 

Hey @aleene can you please take a look?

**Review by philippeauriach — DISMISSED** [review]

**Review by aleene — DISMISSED** [review]

**Comment by teolemon** [comment]
arg, little merge conflict @tejuamirthi 
can you (or someone) fix it and I'll merge just after ?

**Comment by tejuamirthi** [comment]
Hey @aleene, did you check the outcome before the merge commit? Just wanted to confirm

**Comment by tejuamirthi** [comment]
@teolemon. No conflicts now, we can go ahead I guess

**Comment by teolemon** [comment]
@tejuamirthi your diff is now empty ;-)

**Comment by tejuamirthi** [comment]
Yes, just checked. It is empty. Will see what's needed and let you know

**Comment by aleene** [comment]
Ah I made a mistake? Then I must have reintroduced the stores, as I added the new labels.

**Comment by tejuamirthi** [comment]
No problem @aleene 
I have updated the branch

**Comment by tejuamirthi** [comment]
@teolemon You can merge the pr now. Thanks!

**Review by aleene — APPROVED** [review]

**Comment by teolemon** [comment]
Thank you @tejuamirthi :-)

**Comment by tejuamirthi** [comment]
Is this branch bring merged into develop or not @teolemon

**Comment by teolemon** [comment]
Status check is still running

**Comment by tejuamirthi** [comment]
Thank you! @teolemon

**Pull request merged**
