### PR TITLE
Issue 386 native credit

### PR DESCRIPTION
**Pull request by davidlamys**
## PR Description
Rewrite view controller and display contributors in plain table view.

Type of Changes 

- [x] Fixes Issue #[386] https://github.com/openfoodfacts/openfoodfacts-ios/issues/386
- [ ] New feature

Proposed changes
Rewrite view controller and display contributors in plain table view. Tapping on info icon opens link to the contributor.
 
### Before 
Simulator Screen Shot - iPhone 11 Pro - 2019-10-18 at 22 14 24

### After
Simulator Screen Shot - iPhone 11 Pro - 2019-10-18 at 22 55 28

Simulator Screen Shot - iPhone 11 Pro - 2019-10-18 at 22 55 17

## Checklist
 
Make sure you've done all the following (_Put an `x` in the boxes that apply._)
 
 - [x] If you have multiple commits please combine them into one commit by [squashing](https://github.com/todotxt/todo.txt-android/wiki/Squash-All-Commits-Related-to-a-Single-Issue-into-a-Single-Commit) them. 
 - [ ] Code is well documented
 - [ ] Included unit tests for new functionality
 - [x] All user-visible strings are made translatable
 - [ ] Code passes Travis builds in your branch

### CODE REVIEW

**Comment by davidlamys** [comment]
https://github.com/openfoodfacts/openfoodfacts-ios/issues/386

**Comment by aleene** [comment]
Did you check the dark mode? That was the reason the issue was filed in the first place.

You can get rid of the empty separator lines, by adding a uiview below the tableview

**Comment by aleene** [comment]
@teolemon should this be translatable?

**Comment by davidlamys** [comment]
> Did you check the dark mode? That was the reason the issue was filed in the first place.
> 
> You can get rid of the empty separator lines, by adding a uiview below the tableview

done :)

**Comment by aleene** [comment]
@teolemon Should we add more credits?

**Comment by davidlamys** [comment]
Please also note that the first 2 links leads to a 404 page for now 👎 
haha. I can remove the links easily. no problemo.

**Comment by aleene** [comment]
Yep remove them, if you can not find the right one.

**Comment by aleene** [comment]
I'll merge it tomorrow with the changes I am now working on, and get a new build out.

Thanks for your work.

**Pull request merged**
