### PR TITLE
offline products consultation. Fix #35

### LINKED ISSUE #35: Offline mode for consultation
- Download from the server, and store a reduced version (60MB) of Open Food Facts on the device.
- Read from this version when offline, go back to the API when online
- Offer to refresh the database in the settings
- Offer to refresh automatically when on wifi

### PR DESCRIPTION
**Pull request by philippeauriach**
Download offline database once in a month in background
Display download information on home screen
Scan instantly if product available

### CODE REVIEW

**Comment by teolemon** [comment]
@philippeauriach is it good to merge ?

**Comment by philippeauriach** [comment]
@teolemon yes it is ok for me !

**Comment by teolemon** [comment]
Not sure, but wiping the history does wipe the whole DB ?

**Comment by teolemon** [comment]
I was trying to test if scanning offline did add properly to the history.

**Comment by teolemon** [comment]
Let's merge as is.

**Comment by philippeauriach** [comment]
Scanning offline does not add to the history yet

**Pull request merged**
