### PR TITLE
#849 hide nutrition table webview if noNutritionData = "on".

### LINKED ISSUE #849: The nutrition table appears for products without nutrition
The nutrition table appears for products without nutrition. We should hide the table and the take a photo button, and instead put:
"This product does not have any nutrition information on the packaging. If this is an error, please correct it by editing the product"

### PR DESCRIPTION
**Pull request by aleene**
## PR Description
hide nutrition table webview if noNutritionData = "on". 

- [ ] Fixes Issue #849

### CODE REVIEW

**Review by teolemon — DISMISSED** [review]

**Comment by teolemon** [comment]
@aleene conflict arose after I merged your other PR

**Comment by aleene** [comment]
I have to redo part of it. Is needed to be done for the labels editing.

**Comment by aleene** [comment]
Seems ok now

**Comment by teolemon** [comment]
Thanks a lot @aleene merging and releasing to Testflight

**Pull request merged**
