### PR TITLE
Full product edition

### LINKED ISSUE #273: NOVA disappears in online mode
https://barcode.tec-it.com/en/EAN13?data=3560071018085
image
image
https://fr.openfoodfacts.org/produit/3560071018085/pois-chiches-au-sel-de-noirmoutier-carrefour-bio
https://world.openfoodfacts.org/api/v0/product/3560071018085.json (It's there)

### PR DESCRIPTION
**Pull request by philippeauriach**
## PR Description

Allow edition of a product using the same UI as the product creation #190 
This also fix the problem with `nova_group` which can be returned as a string or an int (fix #273 among others)

### WARNING : branch based on branch `xcode_10.2` : if merged, will be merged too

### CODE REVIEW

**Comment by teolemon** [comment]
image

**Comment by teolemon** [comment]
- offline seeems to mostly work
- sending offline product from the offline product area seems to bug (no ongoing upload feedback #269 , as a result double click, and as a result, infinite load since clicking upload products on an empty view, see bug # ? )
- no modifiers (>, <…)

**Comment by teolemon** [comment]
Small Cartfile conflict to solve as regard to ImageViewer

**Comment by philippeauriach** [comment]
@teolemon merged conflict resolved

**Comment by teolemon** [comment]
@philippeauriach @aleene let's merge ?

**Comment by philippeauriach** [comment]
If your functional tests are good, I'm in for the merge !

**Comment by teolemon** [comment]
- the keyboard doesn't allow for `<` ,`=` ,`>`
- when you switch the language, it copies values from the current language (we should try to refresh values from the target language, and if no values, keep the current values, but give a fair warning that they will be saved to the new language.)

**Comment by teolemon** [comment]
I'm merging as is.

**Pull request merged**
