### PR TITLE
 #60 - Display full name of additives, as a list

### PR DESCRIPTION
**Pull request by aubincleme**
* Make sure that the additive row isn’t created inline, but as a list

## PR Description

Describe the changes made and why they were made instead of how they were made.

Type of Changes 

- [x] Fixes Issue #60
- [ ] New feature

Proposed changes

  - Update the display of the additives list following #60

### CODE REVIEW

**Comment by philippeauriach** [comment]
Before, your commit, this method is called in two places,
once in `createSummaryForm()` with `inLine=false`
once in `createIngredientsForm()` with `inLine=true`

After your commit, we now have: 
once in `createSummaryForm()` with `inLine=false`
once in `createIngredientsForm()` with `inLine=false`

I'm not sure of what I wanted to do initially here, but I probably wanted to show a comma-separated list in the summary to gain place, and a bullet point list in the detail ingredients form for more lisibility. 

@teolemon to chose here between two options :
A/ we want both display to be bullet point list, then this PR should update createAdditivesRows to remove the `inLine` parameter as it is unused
B/ we want the summary to be inLine (coma-separated), and the ingredientsForm to be bullet point, then this PR should also modify the call of `createAdditivesRows` in `createSummaryForm` to have inLine=true

**Comment by aubincleme** [comment]
Hi @philippeauriach ; thanks for the quick feedback! I didn’t saw that `createSummaryForm()` was indeed using the same method. It seemed a bit strange to me to have such attribute for a non-public API used only once.

@teolemon what’s your take on this ?

**Comment by teolemon** [comment]
@philippeauriach @aubincleme  Bullet list are the minimum for good readability. People have also been complaining a lot that we still don't show the warning icons like on Android #173

**Comment by aubincleme** [comment]
@philippeauriach d79833c removes the `inLine` parameter from the method. It should be fine now IMO.

**Comment by teolemon** [comment]
thanks @aubincleme , thanks @philippeauriach 
Merging this one

**Pull request merged**
