### PR TITLE
Other language approach

### PR DESCRIPTION
**Pull request by aleene**
## PR Description

This version retains the fields= key in the api-calls. It adds extra fields for language specific json-keys (product_name, generic_name and ingredients_text). All preferred languages specified on the device are used to create these language specific json-keys.

So, a lot of json-keys are added that might result in negative results. When presenting the data the preferred languages are checked to get the best match for the user.

Type of Changes 

- [X ] Fixes Issue #[Please add the issue number here]
- [ ] New feature

Proposed changes

  -
  -
  -
 
## Checklist
 
Make sure you've done all the following (_Put an `x` in the boxes that apply._)
 
 - [ ] If you have multiple commits please combine them into one commit by [squashing](https://github.com/todotxt/todo.txt-android/wiki/Squash-All-Commits-Related-to-a-Single-Issue-into-a-Single-Commit) them. 
 - [ ] Code is well documented
 - [ ] Included unit tests for new functionality
 - [ ] All user-visible strings are made translatable
 - [ ] Code passes Travis builds in your branch

### CODE REVIEW

**Comment by stephanegigandet** [comment]
Hi @aleene,
Sorry I'm just coming back from vacation and I just saw the multilingual issues in the android and ios apps. I'm wondering how "All preferred languages specified on the device" are set? That's a phone wide setting? You have an ordered list of preferred languages?
I'm thinking that we could just do what we do on the web site: use the language of the interface (of the app in this case), and if the language is not available, fall back to the main language of the product.
In that case, we could just have the app ask for product_name, ingredients_text etc. and the server can serve back the requested language.

**Comment by aleene** [comment]
Anyway it is solved, but not so nice.

**Comment by stephanegigandet** [comment]
@aleene : I just added a way to specify the preferred languages in the API, can you just request the product_name, ingredients_text etc. fields (with no language suffix) and then pass a comma separated list of languages in the lc= parameter?
e.g. https://world.openfoodfacts.org/api/v0/product/5411188115533?fields=ingredients_text&lc=ja,nl,de,fr,it,es

**Comment by aleene** [comment]
OK is a bit nicer, I'll do that.

**Comment by aleene** [comment]
Why are so many fields retrieved? Are they really used?

**Pull request merged**
