### PR TITLE
Fixes Create an account and Forgot password button landings in LoginV…

### PR DESCRIPTION
**Pull request by SuzGupta**
## PR Description

Changed the static `baseUrl` replacement in Helpers/URLs.swift to not bring in `codeLang`

Type of Changes 

- [x] Fixes Issue #354
- [ ] New feature

Proposed changes

  - change definition of `baseUrl` in URLs.swift
  
## Checklist
 
Make sure you've done all the following (_Put an `x` in the boxes that apply._)
 
 - [ ] If you have multiple commits please combine them into one commit by [squashing](https://github.com/todotxt/todo.txt-android/wiki/Squash-All-Commits-Related-to-a-Single-Issue-into-a-Single-Commit) them. 
 - [x] Code is well documented (well, I left in the previous definition as a comment at least)
 - [ ] Included unit tests for new functionality
 - [ ] All user-visible strings are made translatable
 - [ ] Code passes Travis builds in your branch (need to learn how to do this)

### CODE REVIEW

**Comment by SuzGupta** [comment]
It's possible this also fixes #341 too. Other links in Settings seem to now work correctly for me (would be good to try from another country); I'll try editing once this is merged and perhaps we have a new TestFlight version? I have not yet created an account because I wanted to do so through the app and this bug needed fixing first :)

**Comment by teolemon** [comment]
@SuzGupta do you know what the codelang passed looklike ? What's the actual network call made to the server ?

**Comment by SuzGupta** [comment]
@teolemon with the original definition of `baseUrl`, the call to `openUrlInApp` attempts to open `https://world-en.openfoodfacts.org/cgi/user.pl` (from `didTipCreateAccountButton`). This redirects to `https://world.openfoodfacts.org`, leaving the user at the top-level landing page, rather than where she expected to go. 

With the proposed change, the user lands as expected when using Create an account, Forgot password?, Frequently Asked Questions and so on/

**Comment by SuzGupta** [comment]
@aleene here too (as on #364), please guide me in what further changes are needed on my part before this can be merged. Thanks!

**Comment by aleene** [comment]
Please resolve the conflicts yourself (if you are able to). Then we can merge.

**Comment by aleene** [comment]
This is an issue of the server redirects. We need another solution in the ios code.

**Comment by SuzGupta** [comment]
I'll have a careful look at how you fixed this, @aleene. My apologies.

**Comment by aleene** [comment]
It is just that english (en) must be handled differently as you discovered.

**Comment by SuzGupta** [comment]
I also think (have not yet looked at your fix) we do want this app to have an awareness of en-US v en-GB and possibly the other variations too, because I think our food labeling is different.

**Comment by aleene** [comment]
It is not possible yet to distinguish between language variants (en-GB vs en-CA) or (zh-CN vs zh-TW or ZH-SG ...) or (pt-PT vs pt-BR). And then there are script variants as well.
The labelling difference is however a difference in locales. If you visit from the US you should see different labelling, etc.

**Pull request merged**
