### PR TITLE
Feature/promo system home #154

### PR DESCRIPTION
**Pull request by philippeauriach**
## PR Description

Type of Changes 
- [x] Fixes Issue #154

Proposed changes: in home "viewwillappear"
  - display the latest tagline in local cache
  - update the local cache with distant tagline
  - refresh displayed tagline with latest version
 
### After
Simulator Screen Shot - iPhone 11 Pro Max - 2020-01-08 at 08 42 37

### CODE REVIEW

**Comment by teolemon** [comment]
Looks good to me. 
It made me realize that:
- lang code for android might not map perfectly those for iOS
- we need to duplicate the file server side to be able to send iOS-specific messages should the need arise.
Will provide a server-side fix for both, the only thing to tweak might be to slightly alter the JSON url

**Comment by teolemon** [comment]
the iOS specific version has been merged and will be deployed at https://world.openfoodfacts.org/files/app/tagline/tagline-off-ios.json

**Comment by philippeauriach** [comment]
> the iOS specific version has been merged and will be deployed at https://world.openfoodfacts.org/files/app/tagline/tagline-off-ios.json

@teolemon exactly the same format ? I can just replace the url, right ?

**Comment by teolemon** [comment]
yup 👍

**Comment by philippeauriach** [comment]
Done then !

**Comment by philippeauriach** [comment]
Yes it is ! Thanks

Philippe Auriach

**Pull request merged**
