### PR TITLE
Feature/sentry crash reports

### PR DESCRIPTION
**Pull request by philippeauriach**
## PR Description

Proposed changes
  - remove all occurences and references to Fabric / Crashlytics
  - send crash reports and errors to Sentry
  - choose version to create in testflight automatically (using the edit or live version from AppStoreConnect)

⚠️ I do not have access to the appstore connect account, so I could not test the "refresh_dsyms" lane (it downloads dsyms, upload them to sentry, and clean up), so I could not verify that my upload_symbols_to_sentry configuration is correct, @teolemon or @aleene could you try ? 

Just run `fastlane refresh_dsyms` in the root of the project. Make sure you have an env variable set for the token : `SENTRY_AUTH_TOKEN` (I can give you the token by MP)

### Clarification on the 'beta' lane changes
In order to make the lane even more autonomous, I removed the need to set the correct version in the xcode project manually.

What the lane does :
- get the version and build number from the live version on the app store
- get the version and build number from the version currently being edited on the app store (if any)
- if there is a version being currently edited in the app store (it means we are working to create a version), then we use this version number. If not, we use the version number from the live version "bumped" by 0.0.1
- for the build number, we take the highest + 1 
- the lane then set those values in the project
- upload to testflight
- commit, tag and push

This way, the version number are always bumped. If we want to make a major release for example, we can still manually set the version number in the xcode project, it will be taken if it is greater than the versions found on the AppStore.

### CODE REVIEW

**Comment by teolemon** [comment]
I'm removing the WIP name, since you marked as ready for review @philippeauriach

**Comment by teolemon** [comment]
@aleene can you give a try to the branch to see if Fastlane works well for you ?

**Comment by aleene** [comment]
I need some help here. I have no experience with fastlane, nor withe github outside the xcode context.

**Comment by philippeauriach** [comment]
I tried to describe what my fastlane lanes do in the readme. To try it you can checkout the branch (feature/sentry-crash-reports), then run the following commands : 
```
bundle install # will install the necessary gem
bundle exec fastlane beta # will bump the version, upload to testflight and commit push
``` 
⚠️ WARNING: this lane will upload a build and tag it and push it. This should normally be used only when actually releasing a build. To test it without sending the build to testflight or tagging the git, you can comment some lines in the `fastfile`, for example : 
```
=begin # line 84
  commit_version_bump(
  ...
  push_to_git_remote
=end # line 93
```

If easier I'm available either here or by MP on slack

**Comment by aleene** [comment]
I already get stuck on `bundle install`.

**Comment by teolemon** [comment]
You need to install Ruby before, I think

**Comment by aleene** [comment]
I have mixed feelings about this. How high do want to make the entry to contributing to OFF? I would vote for staying as close to xcode only as possible.

**Comment by philippeauriach** [comment]
Fastlane are standard tools in the iOS development, and I think ruby is installed on all macs ? Actually there was already a gemfile (so ruby dependencies) before my pr for the previous beta lane. 
Also, it won’t make contributing harder as contributors are not supposed to use the fastlane lanes, as they are only there to push builds to TestFlight, which needs AppStore connect access (and contributors does not have them). 

If ‘bundle install’ is not working, you might not have bundler installed, so I recommend installing it :
‘gem install bundler’

**Comment by aleene** [comment]
Well, I never open the Terminal. I have no idea what to do there. I know a few basic (file) commands and otherwise I follow recipes. And if I get an error (`Could not locate Gemfile or .bundle/ directory`), I am lost. And suggestions on Stackoverflow are then to cryptic, which reminds me why I never want to use Terminal.

**Comment by philippeauriach** [comment]
I’m sorry, I was told you were the one uploading the new versions on TestFlight, and I wrongly deduced that you were using the “beta” lane that does just that. 
So for clarification, when releasing a new build, you do use Xcode / archive / send with the GUI right ?

**Comment by aleene** [comment]
Yes, I use xcode to export and Transporter to upload. Never used fastlane and so it is not setup.

**Review by teolemon — APPROVED** [review]

**Comment by philippeauriach** [comment]
@aleene isn't it merged already?

**Comment by aleene** [comment]
Yes, I am just doing some housekeeping.

**Pull request merged**
