### PR TITLE
Whoops, here's the README.md (so sorry!)

### PR DESCRIPTION
**Pull request by SuzGupta**
## PR Description

Yikes, the previous pull request was actually missing the new README.md, so right now the project doesn't have one, sorry about that

Type of Changes 

- [ ] Fixes Issue #[Please add the issue number here]
- [ ] New feature
- [x] Improves previous PR

Proposed changes

  - Restore README.md, using the file I thought I included previously
 
## Checklist
 
Make sure you've done all the following (_Put an `x` in the boxes that apply._)
 
 - [ ] If you have multiple commits please combine them into one commit by [squashing](https://github.com/todotxt/todo.txt-android/wiki/Squash-All-Commits-Related-to-a-Single-Issue-into-a-Single-Commit) them. 
 - [ ] Code is well documented
 - [ ] Included unit tests for new functionality
 - [ ] All user-visible strings are made translatable
 - [ ] Code passes Travis builds in your branch

### CODE REVIEW

**Comment by SuzGupta** [comment]
@aleene please let me know what I should change before this can be merged. I see there's a merge conflict; should I attempt to deal with this or is this a reviewer/maintainer job? As I am a newbie on the dev side and new to this project, I would welcome some guidance. The end goal on this merge request is just to get this version README.md into the project.

**Comment by aleene** [comment]
Can you resolve?

**Comment by SuzGupta** [comment]
Sigh... I have been playing around with the right way to do this, but I think I have made things messier. Let me close this and try with a new pull request.

**Comment by aleene** [comment]
Be sure to pull in the latest master.

**Pull request closed without merging**
