### PR TITLE
Added Reachability Manager to indicate No Internet Connection 

### PR DESCRIPTION
**Pull request by SahilDhawan**
Added Reachability Manager to indicate No Internet Connection and changed Carthage version of IQKeyboardManager from 5.0.7 to 5.0.4 to avoid Issue 1186

### CODE REVIEW

**Comment by teolemon** [comment]
@SahilDhawan this has conflicts with trunk

**Comment by SahilDhawan** [comment]
What do you refer to when you say that 'it has issue with trunk' ?

**Comment by Tovkal** [comment]
The merge issues can be solved when I merge it, no problem. The real problem is, when I try and build the dependencies with Carthage with Reachability (and all other dependencies currently in the `master` branch), Carthage gets stuck and does not build. I'm not sure how it can be debugged... 

Weird thing is that, when commenting one (any?) of the dependencies, it works. But when all of them are there, it gets stuck. I even tried using the flag `--new-resolver` for `carthage update`, but still it was not working. 

I might have to open an issue at Carthage.

**Comment by teolemon** [comment]
@SahilDhawan can you fix the merge conflict ?

**Comment by teolemon** [comment]
I'm closing this one, as we're going to have offline mode and we now have good fallbacks when offline.

**Pull request closed without merging**
