### PR TITLE
UI Main thread warnings and dutch

### PR DESCRIPTION
**Pull request by aleene**
- [ ] Fixes Issue #307 & #308

### CODE REVIEW

**Comment by teolemon** [comment]
Thanks @aleene :-) Why the duplicate plist ?
@philippeauriach can you review this one ?

**Comment by aleene** [comment]
No idea. Issue with merging the master?

**Comment by philippeauriach** [comment]
Probably. Can safely be deleted (along with its reference in the `project.pbxproj`file)

**Comment by teolemon** [comment]
ok, merging after deleting the extra plist

**Pull request merged**
