### PR TITLE
WIP - fix: Replaced deprecated UIWebView

### LINKED ISSUE #618: Deprecated API Usage - Apple will stop accepting submissions of apps that use UIWebView APIs starting from December 2020
We identified one or more issues with a recent delivery for your app, "Open Food Facts - Product Scan" 3.3 (44). Your delivery was successful, but you may wish to correct the following issues in your next delivery:

ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of apps that use UIWebView APIs starting from December 2020 . See https://developer.apple.com/documentation/uikit/uiwebview for more information.

After you’ve corrected the issues, you can upload a new binary to App Store Connect.

### PR DESCRIPTION
**Pull request by aleene**
## PR Description
The UIWebView entries were replaced with UIWebKit.

Type of Changes 
- [X] Fixes Issue #618

## Proposed changes
There is still an issue with the tableView height of the Nutrition tab. I am not able yo scroll to the bottom. The cell height of the Nutrition table is OK.

There is still an issue with the UIWebKit, which needs to be solved by Apple first. So we can put this pull request on hold as long as that is not yet done.

### CODE REVIEW

**Comment by teolemon** [comment]
@aleene I've changed the base to `develop`. Future PRs will be automatically based on `develop`

**Comment by teolemon** [comment]
@aleene What's the status of this ? Should we close or try to update ?
image

**Comment by aleene** [comment]
Apple will deprecate the old solution, so we should implement it. I wanted to wait to the last moment, as there were issues with apple proposed solution.

If the old solution is no longer supported, we can merge it in.

**Comment by teolemon** [comment]
Ok, let's wait. I rebased the branch for more visibility on your changes.

**Comment by teolemon** [comment]
[CodeFactor](https://www.codefactor.io/repository/github/openfoodfacts/openfoodfacts-ios) found multiple issues last seen at 5d8431b55c8f88ef90d97ef11a83cda6a4d55b49:

#### Prefer at least one space after slashes for comments.
- [ ]  [Sources\Views\Products\Detail\ProductDetailWebViewTableViewCell.swift:69](https://github.com/openfoodfacts/openfoodfacts-ios/blob/5d8431b55c8f88ef90d97ef11a83cda6a4d55b49/Sources/Views/Products/Detail/ProductDetailWebViewTableViewCell.swift#L69)
- [ ]  [Sources\Views\Products\Detail\ProductDetailWebViewTableViewCell.swift:68](https://github.com/openfoodfacts/openfoodfacts-ios/blob/5d8431b55c8f88ef90d97ef11a83cda6a4d55b49/Sources/Views/Products/Detail/ProductDetailWebViewTableViewCell.swift#L68)

**Pull request closed without merging**
