### PR TITLE
Remove double slashes in taxonomies URLs

### LINKED ISSUE #266: Networks calls are slightly incorrect
``` 
XXXX - - [08/Mar/2019:12:02:38 +0100] "GET /data/taxonomies//categories.json HTTP/2.0" 200 1356934 "-" "OpenFoodFacts/3.0 (org.openfoodfacts.scanner; build:11; iOS 12.1.4) Alamofire/4.8.1"
```

### PR DESCRIPTION
**Pull request by cquest**
example: /data/taxonomies//allergens.json -> /data/taxonomies/allergens.json

EDIT: FIXES #266

### CODE REVIEW

**Comment by teolemon** [comment]
Great, a new SWIFT dev :-)

**Comment by teolemon** [comment]
fixes 266. LGTM, @aleene do you concur ?

**Comment by aleene** [comment]
Guess so

**Comment by cquest** [comment]
It is a blind PR... no test done at all, just reading the code and the server logs ;)

**Comment by aleene** [comment]
Would it have resulted in a crash due to a malformed URL string?

**Comment by teolemon** [comment]
@aleene guess not since it's in prod. Good to merge ?

**Comment by teolemon** [comment]
I assume I can merge ? @aleene ?

**Comment by aleene** [comment]
Yes merge seems ok

**Comment by teolemon** [comment]
thanks @aleene let's merge

**Pull request merged**
