### PR TITLE
Set main language upon create

### PR DESCRIPTION
**Pull request by aleene**

### CODE REVIEW

**Comment by teolemon** [comment]
My understanding is that it should solve many of the issues we're seeing in other languages than English, where the main language was set as English on product addition.

**Comment by aleene** [comment]
It should also be a problem for french users. All new products did default to english.

**Comment by aleene** [comment]
By the way can a mass edit repair be done, i.e. all product created by the app, which have english as main language (and no other data in english) and entries in another language are most likely wrong.

**Comment by teolemon** [comment]
https://fr.openfoodfacts.org/date-d-ajout/2020/contributeur/openfoodfacts-contributors/languages

**Comment by teolemon** [comment]
https://de-fr.openfoodfacts.org/date-d-ajout/2020/contributeur/openfoodfacts-contributors/languages

**Pull request merged**
