### PR TITLE
Use xcodegen to generate the xcode project and fix the build: all tests building, unit tests succeeding

### PR DESCRIPTION
**Pull request by acecilia**
This PR makes use of XcodeGen to autogenerate the xcode project, as an initial step towards making the CI setup more robust and less error prone.

It also fixes the builds for all the tests (unit, UI and snapshot) and fixes the unit tests, so they succeed.

### CODE REVIEW

**Comment by acecilia** [comment]
This is now ready for review. Travis is building `OpenFoodFacts`, running the unit tests `OpenFoodFactsTests`, running the UI tests `OpenFoodFactsUITests` and running the snapshot tests `OpenFoodFactsSnapshots` successfully in `8 min 38 sec`.

Note that:

- Several tests of the `OpenFoodFactsTests` target are skipped.
- All tests of the `OpenFoodFactsUITests` target are skipped.

Those tests where disabled in [this PR](https://github.com/openfoodfacts/openfoodfacts-ios/pull/391).

**Comment by aleene** [comment]
Cool that you got things working again.

**Comment by teolemon** [comment]
Well done @acecilia 👌

**Comment by teolemon** [comment]
Merged, thanks a lot :-)

**Comment by acecilia** [comment]
@teolemon would it be possible for you to enable re-running builds? Seems like `master` failed building for no good reason :/

**Comment by teolemon** [comment]
I did it this morning, and the build is now fine 🎉

**Comment by teolemon** [comment]
Feel free to join us on the chat if you haven't done so already @acecilia 
https://slack.openfoodfacts.org

**Pull request merged**
