### PR TITLE
Ingredients analysis fix #321

### LINKED ISSUE #321: Add support for the new server-side Vegan/Vegetarian/Palm Oil detection
Mockups:
image

Add support for the new server-side Vegan/Vegetarian/Palm Oil detection
- [ ] Update the various product queries to include the `ingredients_analysis_tags` field: `https://world.openfoodfacts.org/api/v0/product/3564700459447.json?fields=ingredients_analysis_tags`
{"status":1,"product":{"ingredients_analysis_tags":["en:palm-oil-free","en:non-vegan","en:non-vegetarian"]},"code":"3564700459447","status_verbose":"product found"}
- [ ] We're adding a Detection taxonomy to be able to add new detections on the fly and to reduce hardcoding/simplify implementation:
https://static.openfoodfacts.org/data/taxonomies/ingredients_analysis.json
It has: the tag, the name in various languages, the icon, the color.
- [ ] Explain why it is not vegan/vegetarian thanks to this field: `https://world.openfoodfacts.org/api/v0/product/3564700459447.json?fields=ingredients`

``` {"product":{"ingredients":[{"rank":1,"vegetarian":"no","vegan":"no","text":"Thon albacore","id":"en:yellowfin-tuna"},{"id":"en:water","text":"eau","vegan":"yes","vegetarian":"yes","rank":2},{"rank":3,"id":"en:salt","text":"sel","vegan":"yes","vegetarian":"yes"}]},"code":"3564700459447","status":1,"status_verbose":"product found"}``` 

- [ ] Add the following disclaimer `The analysis is based solely on the ingredients listed and does not take into account processing methods.`

### PR DESCRIPTION
**Pull request by philippeauriach**
Fixes #321 

- added analysis icons above the floating panel (only when down, when up it disappear as it is shown inside the product summary)
- added a "bulletin board" displaying details about the analysis, with a setting switch
- added 3 settings in the settings view to disable analysis display
- technical : updated FloatingPanel lib to latest version, added two new libraries : https://github.com/alexaubry/BulletinBoard and https://github.com/robb/Cartography (iOS 9+ compatible)

## Screenshots : 

Simulator Screen Shot - iPhone 11 - 2020-01-24 at 11 45 38
Simulator Screen Shot - iPhone 11 - 2020-01-24 at 11 45 40
Simulator Screen Shot - iPhone 11 - 2020-01-24 at 11 45 45

### CODE REVIEW

**Comment by teolemon** [comment]
Is it possible to avoid 'hardcoding' settings so that we can add detections on the fly ?

Also, handling grey boxes:
image

**Comment by aleene** [comment]
New build this weekend?

**Comment by teolemon** [comment]
There's still some work on this as mentioned above.
I also spotted an issue:
- Scan a product
- Click on an icon
- Without closing the bubble, scan another product. Try to close the modal: it's not possible anymore. You are stuck forever :-)

**Comment by teolemon** [comment]
If you scan a product, and go in offline mode, the icons of the last online product are retained. They should disappear as soon as we change products.

**Pull request merged**
