### PR TITLE
Standardize hiding/showing of labels for offline product and db response in ScanProductSummaryView

### PR DESCRIPTION
**Pull request by davidlamys**
## PR Description
Standardize hiding/showing of labels for offline product and db response in ScanProductSummaryView in preparation of #405 

Type of Changes 

- [ ] Fixes Issue 
- [ ] New feature

Proposed changes

Currently there are different handling for displaying of offline product and product from the API. ie, we hide certain label in ```RealmOfflineProduct``` when the data driving it is missing, but we don't hide it in the case of a ```Product```. This PR hopes to standardize this before moving on to resolve: https://github.com/openfoodfacts/openfoodfacts-ios/issues/405.
 
Make sure you've done all the following (_Put an `x` in the boxes that apply._)
 
 - [x] If you have multiple commits please combine them into one commit by [squashing]
 - [x] All user-visible strings are made translatable

### CODE REVIEW

**Comment by davidlamys** [comment]
My next step is to extract the methods in the extension and probably introduce a ```ScanProductSummaryViewAdaptor```. Any input guys? :)

**Comment by aleene** [comment]
Handling data always in the same way sounds good.

**Comment by aleene** [comment]
And simplifying into one function is always ok.

**Comment by aleene** [comment]
Did you finish the work on this?

**Comment by davidlamys** [comment]
> Did you finish the work on this?

Hi Aleene, sorry I haven't had the time to work on the original issue. But for the refactoring, I'm at what I believe to be a logical stop for now.

**Pull request merged**
